name: EComposer Storybook

on:
  push:
    branches: [ master ]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Executing remote command to dev env
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        PORT: ${{ secrets.SSH_PORT }}
        script: |
            cd /home/docker/www/docs
            git checkout .
            git checkout master
            git pull origin master